### ISSUE TITLE
Replying to a post doesn't show until after a reload

### ISSUE THREAD

**Issue by NotUnlikeTheWaves** [Southclaws/storyden#14]
Hello, I tried replying to this post on the demo page
https://demo.storyden.org/t/cgufo9uj7aqc37mf14n0-good-morning

The reply didn't show up until I refreshed the page (the text box did get cleared from what I remember)

**Comment by Southclaws** [comment]
Fixed, replies now use `useThreadMutations` hook which triggers an optimistic revalidation which places the new reply immediately in the UI while the network request is sent. If this fails, the text in the input box is kept and the optimistic update is rolled back from the UI. If this succeeds, the reply list is revalidated (re-requested) to refresh any new data from the server.

Thanks for reporting!
