### ISSUE TITLE
Thread dividers looks different on mobile view

### ISSUE THREAD

**Issue by markkkkas** [Southclaws/storyden#15]
![AA057595-4DCE-4C69-9D50-EAEF235AC64E](https://user-images.githubusercontent.com/48568793/233647351-a56aac08-b4cc-4363-bf99-caa4bbf2d522.png)
![D5F261A8-7C21-4004-B38F-3F8EAEAB0894](https://user-images.githubusercontent.com/48568793/233647367-4b3c92ed-6711-4f79-a5eb-7a9e14464b23.png)

**Comment by Southclaws** [comment]
Fixed! Now a card component is used instead of dividers.
