### ISSUE TITLE
building locally - web issues

### ISSUE THREAD

**Issue by rajesh99** [Southclaws/storyden#157]
Hi, I am following
https://www.storyden.org/docs/quickstart/local

Doing the Containerless
I am on Ubuntu22. go version: go1.22.5

Web: 
I tried the web. node version: 22.4.1
yarn dev - This is fine.

I did the 'yarn build'.  I got the following

Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

  ▲ Next.js 14.2.5

   Creating an optimized production build ...
🐼 info [hrtime] Extracted in (392.04ms)
 ✓ Compiled successfully
   Linting and checking validity of types  .Failed to compile.

./src/components/content/ContentComposer/useContentComposer.ts:45:7
Type error: Object literal may only specify known properties, and 'considerAnyAsEmpty' does not exist in type 'Partial<PlaceholderOptions>'.

  43 |       includeChildren: true,
  44 |       showOnlyCurrent: false,
> 45 |       considerAnyAsEmpty: true,
     |       ^
  46 |     }),
  47 |   ];
  48 |
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Southclaws** [comment]
Hi, apologies for this the latest build upgraded a module which changed some types - a new build will be published ASAP to resolve this! Thanks for opening an issue!

**Comment by Southclaws** [comment]
This should be resolved now, latest build is running smoothly on Vercel and Docker images! Let me know if you have any more issues/questions, thanks for checking out Storyden in its early phases of development.
