### ISSUE TITLE
Unintended Scrollbars when Viewing User Panel

### ISSUE THREAD

**Issue by VIRUXE** [Southclaws/storyden#262]
![image](https://github.com/user-attachments/assets/a34ed9e1-265d-484f-b8b5-e68b4abd4787)
![image](https://github.com/user-attachments/assets/1e627c21-c371-4eed-b96f-97aea754bc68)
![image](https://github.com/user-attachments/assets/189cbae5-7b94-444d-a893-e615b495672d)

**Comment by Southclaws** [comment]
This seems like a bug in either https://github.com/cschroeter/park-ui or https://github.com/chakra-ui/ark

should be fixed soon
