### ISSUE TITLE
Changing the password has no feedback

### ISSUE THREAD

**Issue by Bios-Marcel** [Southclaws/storyden#45]
I just changed my password and nothing happened. The page refreshed, but there was no indicator whether the change was successful.

**Comment by Southclaws** [comment]
Thanks for the report! Definitely an oversight on my part, this could do with an inline announcement to inform you the password changed.

I would use a toast but honestly, I've been disliking toast notifications recently as a UI pattern.

**Comment by Southclaws** [comment]
![image](https://github.com/Southclaws/storyden/assets/1636971/8fa3d8bf-bf05-49ec-83f9-b863d94ea7ab)
