### ISSUE TITLE
The emoji picker (reactions) is slow

### ISSUE THREAD

**Issue by Bios-Marcel** [Southclaws/storyden#48]
Both opening and closing of the emoji picker is rather slow. For opening I'd be kind of understanding, but the choppiness during closing it is very weird. Here is a video with visualised mouseclicks.

https://github.com/Southclaws/storyden/assets/19377618/06afa9b0-e15c-479d-a08d-aedefee85e9a

**Comment by Southclaws** [comment]
Oh wow that's terrible! Let's hope emojimart is better!

**Comment by Southclaws** [comment]
Fixed, now using Emojimart and it's much much faster!
