### ISSUE TITLE
Black Image blocks post text 

### ISSUE THREAD

**Issue by ghost** [Southclaws/storyden#7]
![here's an example](https://user-images.githubusercontent.com/62573014/210151118-5f5ba11a-71ee-4d42-9ca8-2e338662a7c7.jpg)
I'm experiencing this on firefox(keep in mind i'm not using default settings, and i have uBlock Origin installed).

**Comment by Southclaws** [comment]
This is definitely the SVG based button of the profile icon breaking out of its bounds somehow:

<img width="145" alt="image" src="https://user-images.githubusercontent.com/1636971/210238458-79a1b5e3-7a69-4ca8-8567-0002e8155ca2.png">

Do you know which settings might cause this? And do you have JavaScript disabled?

**Comment by alloca123** [comment]
i keep javascript enabled, and this issue even happens on base firefox(default configuration, no extensions)

**Comment by Southclaws** [comment]
The new navigation menu should not run into this issue, and I'm also introducing Firefox ESR as the main test browser.
